/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as PredictorRouteImport } from './routes/predictor'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ShareRouteImport } from './routes/share'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileHistoryRouteImport } from './routes/profile.history'
import { Route as ProfileNotificationsRouteImport } from './routes/profile.notifications'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictorRoute = PredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileHistoryRoute = ProfileHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProfileRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/learn': typeof LearnRoute
  '/predictor': typeof PredictorRoute
  '/profile': typeof ProfileRouteWithChildren
  '/share': typeof ShareRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/learn': typeof LearnRoute
  '/predictor': typeof PredictorRoute
  '/share': typeof ShareRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/learn': typeof LearnRoute
  '/predictor': typeof PredictorRoute
  '/profile': typeof ProfileRouteWithChildren
  '/share': typeof ShareRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/learn'
    | '/predictor'
    | '/profile'
    | '/share'
    | '/profile/history'
    | '/profile/notifications'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/learn'
    | '/predictor'
    | '/share'
    | '/profile/history'
    | '/profile/notifications'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/learn'
    | '/predictor'
    | '/profile'
    | '/share'
    | '/profile/history'
    | '/profile/notifications'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LearnRoute: typeof LearnRoute
  PredictorRoute: typeof PredictorRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ShareRoute: typeof ShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictor': {
      id: '/predictor'
      path: '/predictor'
      fullPath: '/predictor'
      preLoaderRoute: typeof PredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/history': {
      id: '/profile/history'
      path: '/history'
      fullPath: '/profile/history'
      preLoaderRoute: typeof ProfileHistoryRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/notifications': {
      id: '/profile/notifications'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof ProfileRoute
    }
  }
}

interface ProfileRouteChildren {
  ProfileHistoryRoute: typeof ProfileHistoryRoute
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileHistoryRoute: ProfileHistoryRoute,
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LearnRoute: LearnRoute,
  PredictorRoute: PredictorRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ShareRoute: ShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
